# Generated by Django 4.2 on 2023-04-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_holidayhomes_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='holiday_homes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.holidayhomes'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='rooom_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='availibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_in',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_out',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rules',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
