# Generated by Django 4.2 on 2023-04-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rooms_holiday_homes_rooms_rooom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayhomes',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
