# Generated by Django 4.2 on 2023-04-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_holidayhomes_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimages',
            name='holiday_homes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.holidayhomes'),
        ),
    ]
